# Este playbook para la ejecuci칩n de los dos microservicios que
# se est치n ejecutando en la m치quina virtual:
# Como hosts seleccione "azure" o "vagrantbox":
---
- hosts: vagrantbox
  # Activamos el escalado de privilegios. Esto nos permitir치 convertirnos en
  # otro usuario en caso de que no tengamos permisos para ejecutar algo:
  become: yes
  tasks:
    # Parar el contenedor del microservicio events:
    - name: Docker | Stop events container
      # Ejecuta el comando en la shell remota:
      shell: docker stop events

    # Parar el contenedor del microservicio tickets:
    - name: Docker | Stop tickets container
      shell: docker stop tickets

    # Parar el contenedor de RabbitMQ:
    - name: Docker | Stop RabbitMQ container
      shell: docker stop rabbit