name: Windows Test

# Lanzar este Workflow cuando se haga un push al repositorio:
on: [push]

jobs:
  build:
    # Los test se realizarán en windows:
    runs-on: windows-latest
    # Se probará con 3 versiones de Python en paralelo:
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
      # "Importamos" la action checkout, que nos permite clonar nuestro
      # repositorio para iniciar los test
      - uses: actions/checkout@v1
      # Configurar la versión de Python correspondiente:
      - name: Set up Python ${{ matrix.python-version }}
      # Para eso importamos otra action predefinida:
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # Instalar mongodb para los tests:
      - name: Start MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: 4.2
      # Instalar las depedencias necesarias para los test:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      # Ejecutar los test: (El microservicio Tickets no es compatible con Windows, por lo que
      # solo testeamos el microservicio Events):
      - name: Test
        run: |
          python -m unittest -v tests/test_events.py tests/test_events_rest.py tests/test_mongo_dm.py
        env:
          DB_URI: ${{ secrets.DB_URI }}
