name: Windows Test

# Lanzar este Workflow cuando se haga un push al repositorio:
on: [push]

jobs:
  build:
    # Los test se realizarán en windows:
    runs-on: windows-latest
    # Se probará con 3 versiones de Python en paralelo:
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
      # "Importamos" la action checkout, que nos permite clonar nuestro
      # repositorio para iniciar los test
      - uses: actions/checkout@v1
      # Configurar la versión de Python correspondiente:
      - name: Set up Python ${{ matrix.python-version }}
      # Para eso importamos otra action predefinida:
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # Instalar las depedencias necesarias para los test:
      - name: Install dependencies
        run: |
          choco install ghostscript
          DIR "C:\Program Files (x86)\"
          python -m pip install --upgrade pip
          make install
      # Ejecutar los test:
      - name: Test
        run: |
          make test
        env:
          DB_URI: ${{ secrets.DB_URI }}